import { Injectable, Logger } from '@nestjs/common';

import type { EventType } from '../../common/events/event-types';
import { ActivityRepository, type ActivityRow } from './activity.repository';

export interface ActivityLogEntry {
  transactionId: string;
  firmId: string;
  /** Null for system-generated events — the worker, a scheduler, an alert. */
  userId: string | null;
  eventType: EventType;
  /** Human-readable, written in code. Never generated by a model (05 §3D). */
  description: string;
  metadata?: Record<string, unknown> | null;
}

/**
 * The one way anything writes to the activity log (05 §3D).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * IT NEVER THROWS.
 *
 * A failed log write must never break the operation it was describing. If
 * Postgres rejects the insert while an attorney is closing a matter, the matter
 * still closes — losing the feed row is bad, losing the close is worse, and a
 * rejected close after the write already committed would be worse still.
 *
 * The cost is that a silent failure is genuinely silent to the caller, so it is
 * logged at ERROR with the correlation ID rather than swallowed. That is the
 * deliberate trade, not an oversight, and it is why this is a service every
 * module calls instead of an insert every module writes.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * A thin wrapper by design — no business rules, no branching on event type.
 * Modules import THIS SERVICE, never `ActivityRepository` (Architecture Rule 2).
 */
@Injectable()
export class ActivityLogService {
  private readonly logger = new Logger(ActivityLogService.name);

  constructor(private readonly repository: ActivityRepository) {}

  async log(entry: ActivityLogEntry): Promise<void> {
    try {
      await this.repository.insert({
        transactionId: entry.transactionId,
        firmId: entry.firmId,
        userId: entry.userId,
        eventType: entry.eventType,
        description: entry.description,
        metadata: entry.metadata ?? null,
      });
    } catch (error) {
      // No PII: the event type and the matter id, never the description, which
      // carries names by construction (CLAUDE.md — never log PII).
      this.logger.error(
        `Activity log write failed for ${entry.eventType} on transaction ${entry.transactionId}`,
        error instanceof Error ? error.stack : String(error),
      );
    }
  }

  async list(
    transactionId: string,
    page: number,
    limit: number,
  ): Promise<{ rows: ActivityRow[]; total: number }> {
    return this.repository.list(transactionId, page, limit);
  }
}
