export const DRAFT_TYPES = [
  'AMENDMENT',
  'EXTENSION_ADDENDUM',
  'EARNEST_MONEY_DEMAND',
  'LEASE_MODIFICATION',
  'CLOSING_INSTRUCTION_LETTER',
  'ENGAGEMENT_LETTER', // carries the AI-disclosure language — Opinion 705
  'STATUS_UPDATE',
  'OTHER',
  // [PHASE 2] PI expansion: DEMAND_LETTER, LEGAL_MEMO, SETTLEMENT_OFFER,
  // COMPLAINT, MOTION
] as const;
export type DraftType = (typeof DRAFT_TYPES)[number];

export const DRAFT_STATUSES = [
  'GENERATING', // BullMQ job in progress
  'READY', // generation complete, awaiting attorney review
  'IN_REVIEW', // attorney has opened the draft
  'APPROVED', // attorney approved, ready to download or send
  'SENT', // attorney marked as sent
  'FAILED', // generation failed after all retries
] as const;
export type DraftStatus = (typeof DRAFT_STATUSES)[number];

export const DRAFT_GENERATED_BY = [
  'AI', // first version, generated by Claude
  'USER', // subsequent versions, attorney edits
] as const;
export type DraftGeneratedBy = (typeof DRAFT_GENERATED_BY)[number];
