import {
  type CallHandler,
  type ExecutionContext,
  Injectable,
  type NestInterceptor,
} from '@nestjs/common';
import * as Sentry from '@sentry/nestjs';
import { ClsService } from 'nestjs-cls';
import type { Observable } from 'rxjs';
import type { Response } from 'express';

/**
 * First interceptor to run (18 §3). Everything downstream — logs, Sentry
 * reports, queue payloads, SSE events — reads the ID from CLS rather than
 * having it threaded through every signature.
 *
 * The ID itself is generated by ClsModule's middleware in CoreModule, which
 * honours an upstream `x-request-id` so a correlation ID survives across
 * service boundaries instead of restarting at our edge. This interceptor does
 * the two things middleware cannot: put it on the response so a caller can
 * quote it, and attach it to the Sentry scope so a report and its log lines
 * join up.
 */
@Injectable()
export class CorrelationIdInterceptor implements NestInterceptor {
  constructor(private readonly cls: ClsService) {}

  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    if (context.getType() === 'http') {
      const requestId = this.cls.getId();
      if (requestId) {
        context.switchToHttp().getResponse<Response>().setHeader('x-request-id', requestId);
        Sentry.getCurrentScope().setTag('request_id', requestId);
      }
    }
    return next.handle();
  }
}
